FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /app

COPY . .

RUN dotnet restore
RUN dotnet publish ./MyFirstCI.Api\MyFirstCI.Api.csproj -c Release -o logout

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build release
WORKDIR /app

ENV ASPNETCORE_URLS=https://+:8080

COPY --from=build /app/out .

EXPOSE 8080

ENTRYPOINT ["dotnet", "MyFirstCI.Api.dll"]
