name: My First Ci Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

env:
  DTN_VER: '7.0.X'

#Жоба -- единица работы
jobs:
  restore:
    name: Restore Dependencies
    runs-on: ubuntu-latest
  
    steps:
     # Шаг вытягивания кода из репозитория
      - name: Get Code From Repo
        uses: actions/checkout@v4
      
      # Тут подготовили среду .Net
      - name: Setup .Net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DTN_VER }}
      
      # Тут восстановили зависимости
      - name: Restore Dependencies
        run: dotnet restore

      # Кэшируем
      - name: Cache Dependenices
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys:
            ${{runner.os}}-nuget-
    
  build:
    name: Build Solution
    runs-on: ubuntu-latest
    needs: restore

    steps:
      # Шаг вытягивания кода из репозитория
      - name: Get Code From Repo
        uses: actions/checkout@v4
      
      # Тут подготовили среду .Net
      - name: Setup .Net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DTN_VER }}

      # Вытягивем с кэша результат выполнения прошлой жобы
      - name: Restore NuGet
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}

      # Билдим решение
      - name: Build Solution
        run: dotnet build --configuration Release --no-restore
        
      # Запускаем тесты
      - name: Run unit tests
        run: dotnet test --no-build --configuration Release --verbosity normal
    
    # build-and-test:
    # runs-on: ubuntu-latest
    # steps:
    #   # Шаг вытягивания кода из репозитория
    #   - name: Get Code From Repo
    #     uses: actions/checkout@v4
      
    #   # Тут подготовили среду .Net
    #   - name: Setup .Net
    #     uses: actions/setup-dotnet@v4
    #     with:
    #       dotnet-version: ${{ env.DTN_VER }}
      
    #   # Тут восстановили зависимости
    #   - name: Restore Dependencies
    #     run: dotnet restore
      
    #   # Билдим решение
    #   - name: Build Solution
    #     run: dotnet build --no-restore --configuration Release
      
    #   # Запускаем тесты
    #   - name: Run unit tests
    #     run: dotnet test --no-build --configuration Release --verbosity normal

#заадча разбить одну жобу на две маленьких, посмотреть как кэшировать промежуточный результат, одна жоба должна подготавливать среду, другая должна билдить и тестировать систему например, главное посмотреть что лучше по скорости одна большая или две маленькие